[settings]
lockfile = true
locked = true
lockfile_platforms = ["linux-x64", "linux-arm64"]

[tools]
go = "1.26.5"
gradle = "9.6.1"
java = "temurin-25.0.4+7.0.LTS"
kotlin = "2.3.20"
python = "3.14.6"
uv = "0.11.7"

[tools."http:flutter"]
version = "3.44.4"
bin_path = "flutter/bin"

[tools."http:flutter".platforms]
linux-x64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.44.4-stable.tar.xz", checksum = "sha256:c853cda0312a162854c481fe6a1bc286d84fbb74bfab7037c39750061dc9b466" }
